const fs =require('fs');
const bodyParser = require('body-parser');
const asyncHandler = require('express-async-handler');
const PDFDocument = require('pdfkit');
const blobStream  = require('blob-stream');
const {join} = require("node:path");

const formPage = asyncHandler(async (req, res) => {
    res.sendFile(join(__dirname, '../../public', 'Form.html'));
});

const getPdf = asyncHandler(async (req, res) => {
    /*const todos = await Todo.find({ user: req.user.id });
    res.status(200).json(todos);*/
});

const sendForm = asyncHandler(async (req, res) => {
    console.log(req.body);
    if (!req.body.firstName || !req.body.lastName) {
        res.status(400);
        throw new Error('Please add first and last name');
    }

    const doc = new PDFDocument();
    let blob = null;
    let docName = req.body.firstName + req.body.lastName + '.pdf';
    //doc.pipe(fs.createWriteStream('../pdf/'+docName));
    const stream = doc.pipe(blobStream());

    doc
        .fontSize(27)
        .text('This PDF has been generated by a Form', 100, 100);

    doc.image(req.body.photo, {
        fit: [300, 300],
        align: 'center',
        valign: 'center'
    });

    doc.text('Name: ' + req.body.firstName + ' ' + req.body.lastName);
    doc.text('Address: ' + req.body.address);
    doc.text('Phone: ' + req.body.phone);
    doc.text('Description: ' + req.body.description);

    doc
        .scale(0.6)
        .translate(470, -380)
        .path('M 250,75 L 323,301 131,161 369,161 177,301 z')
        .fill('red', 'even-odd')
        .restore();

    doc.end();

    stream.on('finish', function() {
        const blob = stream.toBlob('application/pdf');
        const buffer = Buffer.from(blob);

        res.setHeader('Content-Type', 'application/pdf');
        res.setHeader('Content-Disposition', 'attachment; filename=' + req.body.firstName + req.body.lastName + '.pdf');
        res.send(buffer);
    });

    //res.status(200);
})


module.exports = {
    getPdf,
    sendForm,
    formPage
}
